---
- name: "Playing with Ansible and Git"
  hosts: localhost
  connection: local 
  become: no
  
  tasks:
    - name: "just execute a ls -lrt command"
      shell: "ls -lrt"
      register: "output"
    - debug: var=output.stdout_lines
  
    - name: homebrew
      homebrew_installed_packages:
        - htop
  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - ansible-role-shell
    - ansible-role-pip
    - ansible-role-binaries
