---
- hosts: localhost
  become: true

  tasks:
  - name: Install packages with apt
    become: yes
    ansible.builtin.apt:
      name:
        - htop
      state: present
    when: ansible_distribution == "Ubuntu"

  tasks:
  - name: Install packages with brew
    become: yes
    community.general.homebew:
      name:
        - htop
      state: present
    when: ansible_distribution == "MacOSX"
