---
- hosts: localhost
  connection: local
  gather_facts: true

    homebrew_installed_packages:
      - htop

    homebrew_uninstalled_packages: []

  roles:
    - geerlingguy.mac.homebrew
    - geerlingguy.mac.mas
    - ansible-role-shell
    - ansible-role-pip
    - ansible-role-binaries
